name: "Android x64 Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true
env:
  ORT_NIGHTLY_REST_API: "https://feeds.dev.azure.com/aiinfra/PublicPackages/_apis/packaging/Feeds/ORT-Nightly/packages?packageNameQuery=Microsoft.ML.OnnxRuntime&api-version=6.0-preview.1"
  ORT_PACKAGE_NAME: "Microsoft.ML.OnnxRuntime"
  ORT_NIGHTLY_SOURCE: "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/nuget/v3/index.json"
  # ANDROID_ABI: "arm64-v8a"
  ANDROID_ABI: "x86_64"
  ANDROID_NDK_VERSION: "27.2.12479018"  # LTS version
jobs:
  android_x64:
    # Note: linux is the only good option for the Android emulator currently.
    #       it doesn't work on macos-14.
    #         HVF error: HV_UNSUPPORTED
    #       it works on macos-13 but with macos-15 being released soon that isn't a long term solution.
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-genai-Ubuntu2204-AMD-CPU"]
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.6'

      # Check the Android SDK and NDK that we're using
      - name: Check Android SDK and NDK
        run: |
          set -e -x
          uname -m
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls -l $ANDROID_HOME

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --install "ndk;${{ env.ANDROID_NDK_VERSION }}"

          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV
          echo "ANDROID_AVD_HOME=${{ runner.temp }}" >> $GITHUB_ENV

          echo "ANDROID_NDK_LATEST_HOME=$ANDROID_NDK_LATEST_HOME"
          ls -l $ANDROID_HOME/ndk

      - name: Check if emulator is installed and install it if needed
        run: |
          if [ -d "${ANDROID_SDK_ROOT}/emulator" ]; then
              echo "${ANDROID_SDK_ROOT}/emulator exists"
          else
              ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "emulator"
          fi

      # Needed for linux
      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust with rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"
          rustup install 1.86.0
          rustup override set 1.86.0
          rustup component add rust-src
          rustup show active-toolchain

      - name: Install Rust Android Toolchain
        run: |
          rustup target add --toolchain 1.86.0-x86_64-unknown-linux-gnu x86_64-linux-android

      - name: Create Android build
        run: |
          set -e -x
          rm -rf build
          ./build.sh --android --android_api=27 --android_ndk_path=${ANDROID_NDK_HOME} --config=RelWithDebInfo --android_abi=${{ env.ANDROID_ABI }} --parallel --build_java --update

      - name: Run Android build
        run: |
          set -e -x
          ./build.sh --android --android_api=27 --android_ndk_path=${ANDROID_NDK_HOME} --config=RelWithDebInfo --android_abi=${{ env.ANDROID_ABI }} --parallel --build_java --build

      - name: Enable KVM group perms so Android emulator can run
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android tests
        run: |
          set -e -x
          ./build.sh --android --android_api=27 --android_ndk_path=${ANDROID_NDK_HOME} --config=RelWithDebInfo --android_abi=${{ env.ANDROID_ABI }} --parallel --build_java --android_run_emulator --test
